import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google"
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId="891984149642-3d2nvja4mr99hmif5qo7u7smle2ovte5.apps.googleusercontent.com">
          {children}
          <Toaster />
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
